#!/usr/bin/env python

import time
import json
#import syslog
import subprocess
import re
from swsssdk import SonicV2Connector

SLEEP_INTERVAL = 10 # in second
REDIS_HOSTIP = "127.0.0.1"

appDbConnector = SonicV2Connector(host=REDIS_HOSTIP)
appDbConnector.connect("APPL_DB")

def runCommand(command):
    #syslog.syslog(syslog.LOG_INFO, 'cmd: {}'.format(command))
    child = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    ret, err = child.communicate()
    if err == None or err == '':
        return ret
    else:
        #syslog.syslog(syslog.LOG_ERR, 'err: {}'.format(err))
        return ""

def setPeerStatus(peerRemoteAddr, status):
    #newDict = {'BGP_NEIGHBOR': {peerRemoteAddr: {'peer_status': status}}}
    #newJson = json.dumps(newDict)
    #command = ['sonic-cfggen', '-a', newJson, '-w']
    #runCommand(command)
    key = 'BGP_NEIGHBOR:' + peerRemoteAddr
    appDbConnector.set('APPL_DB', key, 'peer_status', status)

def getPeerStatus(peerRemoteAddr):
    command = ['vtysh', '-c', 'show bgp neighbor {}'.format(peerRemoteAddr)]
    ret = runCommand(command)
    pos = re.search('BGP state = [a-zA-Z]*', ret)
    if pos != None:
        return pos.group()[12:len(pos.group())]
    else:
        return ""

def getApplDbPeerStatus(peerRemoteAddr):
    key = 'BGP_NEIGHBOR:' + peerRemoteAddr
    return appDbConnector.get('APPL_DB', key, 'peer_status')

def readConfigDb():
    command = ['sonic-cfggen', '-d', '--print-data']
    return runCommand(command)

def main():
    while True:
        # read config
        sonicCfgJson = readConfigDb()
        # change into dict
        sonicCfgDict = json.loads(sonicCfgJson)

        for (k, v) in sonicCfgDict.items():
            if k == 'BGP_NEIGHBOR':
                bgpNeighbors = v
                for (k, v) in bgpNeighbors.items():
                    peerRemoteAddr = k
                    newStatus = getPeerStatus(k)
                    oldStatus = getApplDbPeerStatus(k)
                    if newStatus != '' and newStatus != oldStatus:
                        setPeerStatus(peerRemoteAddr, newStatus)

        # sleep SLEEP_INTERVAL
        time.sleep(SLEEP_INTERVAL)

if __name__ == '__main__':
    main()